name: run show_my_repositories_details.py

on:
  schedule:
    - cron: '*/2 * * * *' # Runs every 2 minutes

jobs:
  build:
    runs-on: ubuntu-20.04
    steps:
      - name: checkout repo content
        uses: actions/checkout@v3
      - name: setup python
        uses: actions/setup-python@v5
        with:
          python-version: '3.9.13' # install the python version needed    
      - name: install python packages
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt   
      - name: execute py script
        run: python show_my_repositories_details.py
      - name: commit files
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          git add .
          git commit -a "update the list of repositories"
      - name: push changes
        uses: ad-m/github-push-action@v0.6.0
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          branch: main 
